### ISSUE TITLE
SPC Credits Issue

### ISSUE THREAD

**Issue by q3hardcore** [aucguy/aucguy.github.io#1]
You have issues disabled for your SPC repo, so I am reporting this here.

https://github.com/aucguy/spc/blob/master/src/main/resources/mcmod.info
Who is "Lamp-Post"? As far as I can see, they simply added a .gitignore.
You should however credit "303", unless "Lamp-Post" _is_ "303". (I don't think they are)

**Comment by aucguy** [comment]
First of all, thanks for pointing out that issues were disabled for spc (this has been fixed). Secondly, I thought that Lamp-Post was an author for a command (removed from credits). Also, who is 303 and what did he contribute?

**Comment by q3hardcore** [comment]
This is from the Special Thanks section on the SPC thread:
trunksbomb - Active thread user and helped develop some commands for this mod
303 - Contributed a bunch of commands to the mod, and always suggesting new things =)

I'm not sure what commands in particular they contributed, I can't find anything about Lamp-Post.

**Comment by aucguy** [comment]
Added them in. It never occurred to me to check that forum post.
